meta_product_name: "Viens Copine!"
meta_title: "Viens Copine! - Rentre chez toi en toute sécurité"
meta_description: "Viens Copine! est LA webapp qui te permet de rentrer chez toi en toute sécurité après une soirée ou une sortie en ville. Avec Viens Copine, trouve une copiétonne pour t'accompagner sur le chemin de retour. "
meta_image: "viens-copine-webbapp.jpeg"
twitter_account: "@ViensCopine"
